"""Builds and deploys a NerdGraph dashboard snapshot of the scorecard,
directly adapting the proven pattern in
continental-demo/dashboard/deploy_dashboard.py: markdown-table widgets
(md(), the same shape as that script's md()/w() helpers), a dashboardCreate
mutation, and an idempotent find-by-name + dashboardDelete upsert.

Scope limit (see README): this is a point-in-time snapshot re-rendered on
each deploy, not a live trend dashboard -- the scorecard's numbers are
computed in Python, not stored in NRDB, so they can't drive real NRQL-backed
widgets. Turning this into a live/trend dashboard would mean pushing results
into a custom event type via the Event/Insert API, which is future work.
"""

import json

from . import config as config_module
from .nerdgraph import NerdGraphError

TIER_EMOJI = {
    "Absent": "\U0001F534",  # red circle
    "Ad hoc": "\U0001F7E1",  # yellow circle
    "Managed": "\U0001F535",  # blue circle
    "Optimized": "\U0001F7E2",  # green circle
    config_module.UNKNOWN_TIER_LABEL: "\U000026AA",  # white circle
}

DASHBOARD_NAME_TEMPLATE = "AI Readiness Scorecard \u2014 Account {account_id}"


def _md_widget(text, col=1, row=1, width=12, height=6):
    return {
        "title": "",
        "layout": {"column": col, "row": row, "width": width, "height": height},
        "visualization": {"id": "viz.markdown"},
        "rawConfiguration": {"text": text},
    }


def _md_escape_pipe(text):
    return (text or "").replace("|", "\\|").replace("\n", " ")


def _executive_summary_markdown(agg, meta):
    lines = ["## AI Readiness Scorecard"]
    lines.append(
        f"**Account:** {meta.get('account_id')} ({meta.get('region')})  \n"
        f"**Lookback:** {meta.get('lookback_days')} days"
        + (f"  \n**Generated:** {meta['generated_at']}" if meta.get("generated_at") else "")
    )
    lines.append(f"\n### Overall score: {agg['overall_score']} / 10\n")
    lines.append("| Lens | Average score (/10) |")
    lines.append("|---|---|")
    for lens_key, lens_label in config_module.LENS_LABELS.items():
        score = agg["lens_scores"].get(lens_key)
        lines.append(f"| {lens_label} | {score if score is not None else 'n/a'} |")
    return "\n".join(lines)


def _lens_markdown(lens_label, lens_results):
    lines = [f"## {lens_label}", ""]
    lines.append("| Dimension | Tier | Confidence | Evidence | Remediation |")
    lines.append("|---|---|---|---|---|")
    for r in lens_results:
        emoji = TIER_EMOJI.get(r.tier, "")
        lines.append(
            f"| {_md_escape_pipe(r.label)} | {emoji} {r.tier} | {r.confidence} | "
            f"{_md_escape_pipe(r.evidence)} | {_md_escape_pipe(r.remediation)} |"
        )
    return "\n".join(lines)


def build_dashboard_payload(results, agg, meta, name=None):
    dashboard_name = name or DASHBOARD_NAME_TEMPLATE.format(account_id=meta.get("account_id"))

    pages = [
        {"name": "Executive Summary", "widgets": [_md_widget(_executive_summary_markdown(agg, meta))]}
    ]
    for lens_key, lens_label in config_module.LENS_LABELS.items():
        lens_results = [r for r in results if r.lens == lens_key]
        if not lens_results:
            continue
        pages.append(
            {"name": lens_label, "widgets": [_md_widget(_lens_markdown(lens_label, lens_results), height=10)]}
        )

    return {
        "name": dashboard_name,
        "description": "AI Readiness Scorecard snapshot, generated by the ai_readiness CLI.",
        "permissions": "PUBLIC_READ_WRITE",
        "pages": pages,
    }


def find_existing(gql, name):
    """Same shape as continental-demo/dashboard/deploy_dashboard.py:215-223."""
    query = (
        '{ actor { entitySearch(query: "name = \''
        + name.replace("'", "\\'")
        + '\' AND type = \'DASHBOARD\'") { results { entities { guid } } } } }'
    )
    data = gql(query)
    entities = data.get("actor", {}).get("entitySearch", {}).get("results", {}).get("entities", [])
    return [e["guid"] for e in entities]


DASHBOARD_CREATE_MUTATION = """
mutation($accountId: Int!, $dashboard: DashboardInput!) {
  dashboardCreate(accountId: $accountId, dashboard: $dashboard) {
    entityResult { guid name }
    errors { description type }
  }
}
"""

DASHBOARD_DELETE_MUTATION = "mutation($g: EntityGuid!) { dashboardDelete(guid: $g) { status } }"


def deploy(gql, account_id, results, agg, meta, name=None):
    """Upserts the dashboard by name: deletes any existing dashboard with the
    same name, then creates a fresh one. Returns {"guid": ..., "name": ...}."""
    payload = build_dashboard_payload(results, agg, meta, name=name)

    for guid in find_existing(gql, payload["name"]):
        gql(DASHBOARD_DELETE_MUTATION, {"g": guid})

    data = gql(DASHBOARD_CREATE_MUTATION, {"accountId": account_id, "dashboard": payload})
    result = data.get("dashboardCreate", {})
    if result.get("errors"):
        raise NerdGraphError(json.dumps(result["errors"]))
    return result["entityResult"]
