"""Builds and deploys a NerdGraph dashboard snapshot of the scorecard,
directly adapting the proven pattern in
reference-repo-a/dashboard/deploy_dashboard.py: markdown-table widgets
(md(), the same shape as that script's md()/w() helpers) and an idempotent
find-by-name + dashboardUpdate upsert.

Scope limit (see README): this is a point-in-time snapshot re-rendered on
each deploy, not a live trend dashboard -- the scorecard's numbers are
computed in Python, not stored in NRDB, so they can't drive real NRQL-backed
widgets. Turning this into a live/trend dashboard would mean pushing results
into a custom event type via the Event/Insert API, which is future work.
"""

import json

from . import config as config_module
from .nerdgraph import NerdGraphError

TIER_EMOJI = {
    "Absent": "\U0001F534",  # red circle
    "Ad hoc": "\U0001F7E1",  # yellow circle
    "Managed": "\U0001F535",  # blue circle
    "Optimized": "\U0001F7E2",  # green circle
    config_module.UNKNOWN_TIER_LABEL: "\U000026AA",  # white circle -- couldn't measure
    config_module.NOT_APPLICABLE_TIER_LABEL: "\U00002796",  # heavy minus -- measured, nothing to grade
}

DASHBOARD_NAME_TEMPLATE = "AI Readiness Scorecard \u2014 Account {account_id}"


def _md_widget(text, col=1, row=1, width=12, height=6):
    return {
        "title": "",
        "layout": {"column": col, "row": row, "width": width, "height": height},
        "visualization": {"id": "viz.markdown"},
        "rawConfiguration": {"text": text},
    }


def _md_escape_pipe(text):
    return (text or "").replace("|", "\\|").replace("\n", " ")


def _executive_summary_markdown(agg, meta):
    lines = ["## AI Readiness Scorecard"]
    if meta.get("mock"):
        lines.append(
            "⚠️ **MOCK DATA -- not a real account.** Every number here is canned fixture "
            "data; this payload was built with `--mock` and should never be deployed as if it "
            "reflects a real customer.\n"
        )
    lines.append(
        f"**Account:** {meta.get('account_id')} ({meta.get('region')})  \n"
        f"**Lookback:** {meta.get('lookback_days')} days"
        + (f"  \n**Generated:** {meta['generated_at']}" if meta.get("generated_at") else "")
        + (
            f"  \n**Tool:** v{meta['tool_version']}, config `{meta['config_fingerprint']}`"
            if meta.get("tool_version") else ""
        )
    )
    lines.append(
        f"\n### Overall score: {agg['overall_score']} / 10 "
        f"(scored {agg['scored_count']} of {agg['total_count']} dimensions)\n"
    )
    lines.append("| Lens | Average score (/10) | Scored |")
    lines.append("|---|---|---|")
    for lens_key, lens_label in config_module.LENS_LABELS.items():
        score = agg["lens_scores"].get(lens_key)
        counts = agg["lens_counts"].get(lens_key, {"scored": 0, "total": 0})
        lines.append(
            f"| {lens_label} | {score if score is not None else 'n/a'} | "
            f"{counts['scored']} of {counts['total']} |"
        )
    return "\n".join(lines)


def _lens_markdown(lens_label, lens_results):
    lines = [f"## {lens_label}", ""]
    lines.append("| Dimension | Tier | Confidence | Evidence | Remediation |")
    lines.append("|---|---|---|---|---|")
    for r in lens_results:
        emoji = TIER_EMOJI.get(r.tier, "")
        lines.append(
            f"| {_md_escape_pipe(r.label)} | {emoji} {r.tier} | {r.confidence} | "
            f"{_md_escape_pipe(r.evidence)} | {_md_escape_pipe(r.remediation)} |"
        )
    return "\n".join(lines)


def build_dashboard_payload(results, agg, meta, name=None):
    dashboard_name = name or DASHBOARD_NAME_TEMPLATE.format(account_id=meta.get("account_id"))

    pages = [
        {"name": "Executive Summary", "widgets": [_md_widget(_executive_summary_markdown(agg, meta))]}
    ]
    for lens_key, lens_label in config_module.LENS_LABELS.items():
        lens_results = [r for r in results if r.lens == lens_key]
        if not lens_results:
            continue
        pages.append(
            {"name": lens_label, "widgets": [_md_widget(_lens_markdown(lens_label, lens_results), height=10)]}
        )

    return {
        "name": dashboard_name,
        "description": "AI Readiness Scorecard snapshot, generated by the ai_readiness CLI.",
        "permissions": "PUBLIC_READ_WRITE",
        "pages": pages,
    }


FIND_EXISTING_QUERY = """
query($query: String!) {
  actor { entitySearch(query: $query) { results { entities { guid } } } }
}
"""


def find_existing(gql, account_id, name):
    """Same shape as reference-repo-a/dashboard/deploy_dashboard.py:215-223,
    plus an accountId scope (same pattern as dashboards_logs.py's
    DASHBOARDS_QUERY) so a multi-account user key can't match a same-named
    dashboard sitting in a different account. `name` travels as a bound
    GraphQL variable rather than being spliced into the query document text,
    so it can't break out of the document regardless of what characters a
    customer name contains -- the only escaping still needed is for the
    single quote inside the entitySearch query-language string itself."""
    escaped_name = name.replace("\\", "\\\\").replace("'", "\\'")
    search_query = f"type = 'DASHBOARD' AND accountId = {account_id} AND name = '{escaped_name}'"
    data = gql(FIND_EXISTING_QUERY, {"query": search_query})
    entities = data.get("actor", {}).get("entitySearch", {}).get("results", {}).get("entities", [])
    return [e["guid"] for e in entities]


DASHBOARD_CREATE_MUTATION = """
mutation($accountId: Int!, $dashboard: DashboardInput!) {
  dashboardCreate(accountId: $accountId, dashboard: $dashboard) {
    entityResult { guid name }
    errors { description type }
  }
}
"""

DASHBOARD_UPDATE_MUTATION = """
mutation($guid: EntityGuid!, $dashboard: DashboardInput!) {
  dashboardUpdate(guid: $guid, dashboard: $dashboard) {
    entityResult { guid name }
    errors { description type }
  }
}
"""


def deploy(gql, account_id, results, agg, meta, name=None):
    """Upserts the dashboard by name, scoped to account_id: updates the
    existing dashboard's GUID in place if one is found, otherwise creates a
    new one. Returns {"guid": ..., "name": ...}. Updating in place (rather
    than delete-then-create) keeps the GUID -- and therefore the link handed
    to a customer -- stable across reruns."""
    payload = build_dashboard_payload(results, agg, meta, name=name)

    existing_guids = find_existing(gql, account_id, payload["name"])
    if existing_guids:
        data = gql(DASHBOARD_UPDATE_MUTATION, {"guid": existing_guids[0], "dashboard": payload})
        result = data.get("dashboardUpdate", {})
    else:
        data = gql(DASHBOARD_CREATE_MUTATION, {"accountId": account_id, "dashboard": payload})
        result = data.get("dashboardCreate", {})

    if result.get("errors"):
        raise NerdGraphError(json.dumps(result["errors"]))
    return result["entityResult"]
